### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by alexkyllo**
Test out these changes on https://curatescience-staging.herokuapp.com/beta/

Frontend changes for https://github.com/ScienceCommons/api/issues/188

Also fixed https://github.com/ScienceCommons/api/issues/154

### CODE REVIEW

**Comment by alexkyllo** [comment]
OK I just pushed a commit to fix the additional issues you identified (mainly searching wasn't working for logged out users) and it will be live on the staging site in a few minutes, once Travis finishes deploying it.

**Comment by eplebel** [comment]
great, it works! thx so much!!

**Comment by eplebel** [comment]
Actually, I just noticed that article content doesn't seem to be loading (for unauthenticated user) on my smartphone chrome

**Comment by eplebel** [comment]
Also, could you re-add the "Add replication icon" within the replication table and have a hover tooltip that states "Please log in to add a replication" ("log in" hyperlinked of course)?

**Comment by alexkyllo** [comment]
*Also, could you re-add the "Add replication icon" within the replication table and have a hover tooltip that states "Please log in to add a replication" ("log in" hyperlinked of course)?*

Done!

*Actually, I just noticed that article content doesn't seem to be loading (for unauthenticated user) on my smartphone chrome v38.0.2125.114*

I can't reproduce this issue on my own smartphone (Google Nexus 5) nor on Chrome's Device Mode. What model is your smartphone? Can you reproduce and take a screenshot or something?
The app loads a lot of javascript (over a MB) and I suppose if you have a slow or unreliable connection you may have issues loading content.

**Comment by eplebel** [comment]
ah ok article content *does* appear to be loading correctly on my
smartphone (samsung galaxy s4); however, when i try to go to homepage (
https://curatescience-staging.herokuapp.com/beta/#/), it hangs for a long
time, and I cannot search (though I *can* successfully search from the
article page!)

**Pull request merged**
